"use client";

import { useEffect, useMemo, useState } from "react";
import { Archive, ArrowLeft, ChevronDown, ExternalLink, ImageOff, Plus, Search, ShieldCheck, SlidersHorizontal, X } from "lucide-react";

type Grader = "Degree" | "PSA" | "CGC" | "PGS" | "Collect Direct";
type Card = { id:string; grader:Grader; certNumber:string; grade:string; year:string; brand:string; set:string; subject:string; cardNumber:string; variant:string; frontImageUrl:string; backImageUrl:string; certUrl:string; population:number|null; graderSpecific:Record<string,unknown>; addedAt:string; manual?:boolean };
const seed: Card[] = [
  {id:"demo-1",grader:"PSA",certNumber:"DEMO-PSA-001",grade:"10",year:"2023",brand:"Topps",set:"Chrome",subject:"Collection preview",cardNumber:"#1",variant:"Refractor",frontImageUrl:"",backImageUrl:"",certUrl:"",population:341,graderSpecific:{label:"Gem Mint"},addedAt:"2026-09-14"},
  {id:"demo-2",grader:"CGC",certNumber:"DEMO-CGC-002",grade:"9.5",year:"2022",brand:"Pokémon",set:"Silver Tempest",subject:"Sample slab",cardNumber:"#184",variant:"Full Art",frontImageUrl:"",backImageUrl:"",certUrl:"",population:null,graderSpecific:{},addedAt:"2026-09-13"},
  {id:"demo-3",grader:"Degree",certNumber:"DEMO-DEG-003",grade:"9",year:"2021",brand:"Panini",set:"Prizm",subject:"Demo card",cardNumber:"#7",variant:"Silver",frontImageUrl:"",backImageUrl:"",certUrl:"",population:22,graderSpecific:{centering:"95%"},addedAt:"2026-09-12"},
];
const graders: Grader[] = ["Degree","PSA","CGC","PGS","Collect Direct"];
const empty = (grader:Grader, certNumber:string):Card => ({id:crypto.randomUUID(),grader,certNumber,grade:"",year:"",brand:"",set:"",subject:"",cardNumber:"",variant:"",frontImageUrl:"",backImageUrl:"",certUrl:"",population:null,graderSpecific:{},addedAt:new Date().toISOString(),manual:true});

function CardImage({card,large=false}:{card:Card;large?:boolean}) { const [failed,setFailed]=useState(false); if (!card.frontImageUrl || failed) return <div className={`image-placeholder ${large?"large":""}`}><ImageOff/><span>Image unavailable</span></div>; return <img className={`slab-image ${large?"large":""}`} src={card.frontImageUrl} alt={`${card.subject} graded card`} onError={()=>setFailed(true)}/>; }

export default function Home(){
  const [cards,setCards]=useState<Card[]>(seed),[hydrated,setHydrated]=useState(false),[query,setQuery]=useState(""),[grader,setGrader]=useState("All graders"),[grade,setGrade]=useState("All grades"),[sort,setSort]=useState("Newest"),[addOpen,setAddOpen]=useState(false),[detail,setDetail]=useState<Card|null>(null),[step,setStep]=useState<"lookup"|"failed"|"manual">("lookup"),[lookupGrader,setLookupGrader]=useState<Grader>("Degree"),[cert,setCert]=useState(""),[draft,setDraft]=useState<Card|null>(null),[notice,setNotice]=useState("");
  const filtered=useMemo(()=>cards.filter(c=>{const hay=[c.subject,c.set,c.brand,c.certNumber,c.cardNumber,c.grader].join(" ").toLowerCase();return hay.includes(query.toLowerCase())&&(grader==="All graders"||c.grader===grader)&&(grade==="All grades"||c.grade===grade)}).sort((a,b)=>sort==="Oldest"?a.addedAt.localeCompare(b.addedAt):sort==="Grade high"?Number(b.grade)-Number(a.grade):b.addedAt.localeCompare(a.addedAt)),[cards,query,grader,grade,sort]);
  useEffect(()=>{try{const saved=localStorage.getItem("slabvault.cards.v1");if(saved)setCards(JSON.parse(saved))}catch{}finally{setHydrated(true)}},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("slabvault.cards.v1",JSON.stringify(cards))},[cards,hydrated]);
  useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void context.registerTool({name:"start_card_entry",title:"Start card entry",description:"Open the Add Card flow with a grader and certification number ready to verify.",inputSchema:{type:"object",properties:{grader:{type:"string",enum:graders},certNumber:{type:"string"}},required:["grader","certNumber"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const value=input as {grader?:Grader;certNumber?:string};if(!value.certNumber?.trim()||!graders.includes(value.grader as Grader))throw new Error("A supported grader and certification number are required.");setLookupGrader(value.grader as Grader);setCert(value.certNumber.trim());setStep("lookup");setAddOpen(true);return{status:"ready",grader:value.grader,certNumber:value.certNumber.trim()}}},{signal:lifecycle.signal});return()=>lifecycle.abort()},[]);
  function beginLookup(){setNotice("");const duplicate=cards.find(c=>c.grader===lookupGrader&&c.certNumber===cert.trim());if(duplicate){setDetail(duplicate);setAddOpen(false);setNotice("This slab is already in your collection.");return}if(!cert.trim()){setNotice("Enter the certification number first.");return}setStep("failed")}
  function beginManual(){setDraft(empty(lookupGrader,cert.trim()));setStep("manual")}
  function update(key:keyof Card,value:string){setDraft(d=>d?{...d,[key]:value}:d)}
  function save(){if(!draft?.subject||!draft.grade){setNotice("Add at least a subject and grade.");return}setCards(c=>[draft,...c]);setAddOpen(false);setStep("lookup");setCert("");setNotice("Card added to your collection.")}
  return <main><header className="topbar"><div className="brand"><span className="brand-mark"><ShieldCheck/></span><div><b>SLAB<span>VAULT</span></b><small>GRADED COLLECTION</small></div></div><button className="primary desktop-add" onClick={()=>setAddOpen(true)}><Plus/> Add card</button></header><section className="shell"><div className="intro"><div><p className="eyebrow">THE COLLECTION</p><h1>Your graded cards,<br/><em>all in one place.</em></h1></div><div className="count"><strong>{cards.length}</strong><span>TOTAL SLABS</span></div></div>{notice&&<div className="notice">{notice}<button aria-label="Dismiss" onClick={()=>setNotice("")}><X/></button></div>}<div className="toolbar"><label className="search"><Search/><input aria-label="Search collection" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cards, sets, certs…"/></label><div className="filters"><label><SlidersHorizontal/><select value={grader} onChange={e=>setGrader(e.target.value)}><option>All graders</option>{graders.map(g=><option key={g}>{g}</option>)}</select><ChevronDown/></label><label><select value={grade} onChange={e=>setGrade(e.target.value)}><option>All grades</option>{["10","9.5","9","8.5","8","7"].map(g=><option key={g}>{g}</option>)}</select><ChevronDown/></label><label><select value={sort} onChange={e=>setSort(e.target.value)}><option>Newest</option><option>Oldest</option><option>Grade high</option></select><ChevronDown/></label></div></div><div className="result-head"><span>{filtered.length} {filtered.length===1?"SLAB":"SLABS"}</span><i/></div>{filtered.length?<div className="card-grid">{filtered.map(card=><button className="slab-card" key={card.id} onClick={()=>setDetail(card)}><div className="card-art"><CardImage card={card}/><span className={`grader-pill ${card.grader.toLowerCase().replace(" ","-")}`}>{card.grader}</span></div><div className="card-copy"><div className="grade-block"><strong>{card.grade}</strong><span>GRADE</span></div><div className="card-name"><h2>{card.subject}</h2><p>{card.year} {card.brand} · {card.set}</p><small>{card.cardNumber} {card.variant&&`· ${card.variant}`}</small></div><code>{card.certNumber}</code></div></button>)}</div>:<div className="empty"><Archive/><h2>No slabs found</h2><p>Try clearing a filter or add a graded card.</p></div>}</section><button className="floating-add" onClick={()=>setAddOpen(true)}><Plus/> Add card</button>
  {addOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setAddOpen(false)}}><section className="modal add-modal"><button className="close" onClick={()=>setAddOpen(false)}><X/></button><p className="eyebrow">NEW SLAB</p><h2>{step==="manual"?"Enter card details":"Add to your vault"}</h2>{step==="lookup"&&<><p className="muted">Start with the grading company and certification number.</p><label className="field">Grading company<select value={lookupGrader} onChange={e=>setLookupGrader(e.target.value as Grader)}>{graders.map(g=><option key={g}>{g}</option>)}</select></label><label className="field">Certification number<input value={cert} onChange={e=>setCert(e.target.value)} placeholder="e.g. 00409451" inputMode="numeric"/></label><button className="primary wide" onClick={beginLookup}>Look up certificate</button></>}{step==="failed"&&<div className="lookup-failed"><div className="status-icon">!</div><h3>We couldn’t automatically retrieve this certification.</h3><p>The grader may block automated access or the lookup service may be unavailable. Nothing has been added yet.</p><button className="primary wide" onClick={beginManual}>Enter manually</button><button className="text-button" onClick={()=>setStep("lookup")}><ArrowLeft/> Try another certificate</button></div>}{step==="manual"&&draft&&<><div className="manual-grid">{([['subject','Subject / card name'],['grade','Grade'],['year','Year'],['brand','Brand'],['set','Set'],['cardNumber','Card number'],['variant','Variant'],['frontImageUrl','Front image URL'],['backImageUrl','Back image URL'],['certUrl','Certification page URL']] as [keyof Card,string][]).map(([key,label])=><label className={`field ${key.includes('Url')?'full':''}`} key={key}>{label}<input value={String(draft[key]??"")} onChange={e=>update(key,e.target.value)}/></label>)}</div><div className="identity"><span>{draft.grader}</span><code>{draft.certNumber}</code></div><button className="primary wide" onClick={save}>Add to collection</button></>}</section></div>}
  {detail&&<div className="modal-backdrop"><section className="modal detail-modal"><button className="close" onClick={()=>setDetail(null)}><X/></button><div className="detail-image"><CardImage card={detail} large/></div><div className="detail-copy"><span className="grader-pill">{detail.grader}</span><h2>{detail.subject}</h2><p>{detail.year} {detail.brand} · {detail.set} {detail.cardNumber}</p><div className="big-grade"><strong>{detail.grade}</strong><span>GRADE</span></div><dl><div><dt>Certification</dt><dd>{detail.certNumber}</dd></div><div><dt>Variant</dt><dd>{detail.variant||"—"}</dd></div><div><dt>Population</dt><dd>{detail.population??"Not available"}</dd></div><div><dt>Entry</dt><dd>{detail.manual?"Manual":"Verified lookup"}</dd></div>{Object.entries(detail.graderSpecific).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl>{detail.certUrl&&<a className="primary link" target="_blank" href={detail.certUrl}>Open certification <ExternalLink/></a>}</div></section></div>}</main>}
